import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { livePriorFindings } from "/tmp/flow-jev-overnight-20260924/flow-validation-spill/src/domain/review-findings.js";
import { createFileSourceIdentityProvider } from "/tmp/flow-jev-overnight-20260924/flow-validation-spill/src/infrastructure/fs/source-identity.js";
const root="/tmp/flow-jev-overnight-20260924/echo-recording-fixed-host";
const workspace="/tmp/flow-jev-overnight-20260924/echo-recording-gate-observed";
const session=JSON.parse(await readFile(root+"/repeated-review-checkpoint-rev19.json","utf8"));
const messages=JSON.parse(await readFile(root+"/parent-after-recovery.json","utf8"));
const proposal=messages.flatMap((m:any)=>m.parts??[]).filter((p:any)=>p.type==="tool"&&p.tool==="flow_status").map((p:any)=>p.state?.input?.recoveryProposal).find(Boolean);
if(!proposal)throw new Error("No observed manager proposal");
const sourceDigest=await createFileSourceIdentityProvider(workspace).computeSourceDigest();
const hash=(value:unknown)=>createHash("sha256").update(JSON.stringify(value)).digest("hex");
const findingFeatureIds=new Set(proposal.candidates.map((c:any)=>c.featureId));
const findings=[...findingFeatureIds].flatMap((id:any)=>livePriorFindings(session,id).map((f:any)=>({id:f.findingId,summary:f.summary,evidence:f.evidence??""})));
const packet={sessionId:session.id,revision:session.revision,sourceDigest,goal:session.goal,planDigest:hash({id:session.id,goal:session.goal,plan:session.plan,approval:session.approval}),rubric:"recovery-v1",findings,candidates:proposal.candidates};
const packetDigest=hash(packet);
const observed=messages.flatMap((m:any)=>m.parts??[]).filter((p:any)=>p.type==="tool"&&p.tool==="flow_status").map((p:any)=>{try{return JSON.parse(p.state.output)?.workflowData?.recovery?.packetDigest}catch{return null}}).find(Boolean);
await writeFile(root+"/observed-decision-packet.json",JSON.stringify({schemaVersion:1,packet,managerProposal:proposal,packetDigest,observedPacketDigest:observed,matches:packetDigest===observed},null,2)+"\n");
process.stdout.write(JSON.stringify({packetDigest,observed,matches:packetDigest===observed,findings:findings.length,candidates:proposal.candidates.length,sourceDigest})+"\n");
